package com.cs.dao;

import com.cs.entities.ClientMaster;
import com.cs.entities.ClientMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClientMasterMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	long countByExample(ClientMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int deleteByExample(ClientMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int deleteByPrimaryKey(Integer clientId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int insert(ClientMaster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int insertSelective(ClientMaster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	List<ClientMaster> selectByExample(ClientMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	ClientMaster selectByPrimaryKey(Integer clientId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int updateByExampleSelective(@Param("record") ClientMaster record, @Param("example") ClientMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int updateByExample(@Param("record") ClientMaster record, @Param("example") ClientMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int updateByPrimaryKeySelective(ClientMaster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int updateByPrimaryKey(ClientMaster record);
}