package com.cs.dao;

import com.cs.entities.ExecutionOrderTxn;
import com.cs.entities.ExecutionOrderTxnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExecutionOrderTxnMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	long countByExample(ExecutionOrderTxnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int deleteByExample(ExecutionOrderTxnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int deleteByPrimaryKey(Integer orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int insert(ExecutionOrderTxn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int insertSelective(ExecutionOrderTxn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	List<ExecutionOrderTxn> selectByExample(ExecutionOrderTxnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	ExecutionOrderTxn selectByPrimaryKey(Integer orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int updateByExampleSelective(@Param("record") ExecutionOrderTxn record,
			@Param("example") ExecutionOrderTxnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int updateByExample(@Param("record") ExecutionOrderTxn record, @Param("example") ExecutionOrderTxnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int updateByPrimaryKeySelective(ExecutionOrderTxn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int updateByPrimaryKey(ExecutionOrderTxn record);
}