package com.cs.dao;

import com.cs.entities.ExecutionMst;
import com.cs.entities.ExecutionMstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExecutionMstMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	long countByExample(ExecutionMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	int deleteByExample(ExecutionMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	int deleteByPrimaryKey(Integer executionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	int insert(ExecutionMst record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	int insertSelective(ExecutionMst record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	List<ExecutionMst> selectByExample(ExecutionMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	ExecutionMst selectByPrimaryKey(Integer executionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	int updateByExampleSelective(@Param("record") ExecutionMst record, @Param("example") ExecutionMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	int updateByExample(@Param("record") ExecutionMst record, @Param("example") ExecutionMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	int updateByPrimaryKeySelective(ExecutionMst record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	int updateByPrimaryKey(ExecutionMst record);
}