package com.cs.dao;

import com.cs.entities.OrderBook;
import com.cs.entities.OrderBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderBookMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	long countByExample(OrderBookExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int deleteByExample(OrderBookExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int deleteByPrimaryKey(Integer orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int insert(OrderBook record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int insertSelective(OrderBook record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	List<OrderBook> selectByExample(OrderBookExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	OrderBook selectByPrimaryKey(Integer orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int updateByExampleSelective(@Param("record") OrderBook record, @Param("example") OrderBookExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int updateByExample(@Param("record") OrderBook record, @Param("example") OrderBookExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int updateByPrimaryKeySelective(OrderBook record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	int updateByPrimaryKey(OrderBook record);
}