package com.cs.entities;

import java.util.ArrayList;
import java.util.List;

public class ClientMasterExample extends BaseEntityExample{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public ClientMasterExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andClientIdIsNull() {
			addCriterion("client_id is null");
			return (Criteria) this;
		}

		public Criteria andClientIdIsNotNull() {
			addCriterion("client_id is not null");
			return (Criteria) this;
		}

		public Criteria andClientIdEqualTo(Integer value) {
			addCriterion("client_id =", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdNotEqualTo(Integer value) {
			addCriterion("client_id <>", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdGreaterThan(Integer value) {
			addCriterion("client_id >", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("client_id >=", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdLessThan(Integer value) {
			addCriterion("client_id <", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdLessThanOrEqualTo(Integer value) {
			addCriterion("client_id <=", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdIn(List<Integer> values) {
			addCriterion("client_id in", values, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdNotIn(List<Integer> values) {
			addCriterion("client_id not in", values, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdBetween(Integer value1, Integer value2) {
			addCriterion("client_id between", value1, value2, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdNotBetween(Integer value1, Integer value2) {
			addCriterion("client_id not between", value1, value2, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientNameIsNull() {
			addCriterion("client_name is null");
			return (Criteria) this;
		}

		public Criteria andClientNameIsNotNull() {
			addCriterion("client_name is not null");
			return (Criteria) this;
		}

		public Criteria andClientNameEqualTo(String value) {
			addCriterion("client_name =", value, "clientName");
			return (Criteria) this;
		}

		public Criteria andClientNameNotEqualTo(String value) {
			addCriterion("client_name <>", value, "clientName");
			return (Criteria) this;
		}

		public Criteria andClientNameGreaterThan(String value) {
			addCriterion("client_name >", value, "clientName");
			return (Criteria) this;
		}

		public Criteria andClientNameGreaterThanOrEqualTo(String value) {
			addCriterion("client_name >=", value, "clientName");
			return (Criteria) this;
		}

		public Criteria andClientNameLessThan(String value) {
			addCriterion("client_name <", value, "clientName");
			return (Criteria) this;
		}

		public Criteria andClientNameLessThanOrEqualTo(String value) {
			addCriterion("client_name <=", value, "clientName");
			return (Criteria) this;
		}

		public Criteria andClientNameLike(String value) {
			addCriterion("client_name like", value, "clientName");
			return (Criteria) this;
		}

		public Criteria andClientNameNotLike(String value) {
			addCriterion("client_name not like", value, "clientName");
			return (Criteria) this;
		}

		public Criteria andClientNameIn(List<String> values) {
			addCriterion("client_name in", values, "clientName");
			return (Criteria) this;
		}

		public Criteria andClientNameNotIn(List<String> values) {
			addCriterion("client_name not in", values, "clientName");
			return (Criteria) this;
		}

		public Criteria andClientNameBetween(String value1, String value2) {
			addCriterion("client_name between", value1, value2, "clientName");
			return (Criteria) this;
		}

		public Criteria andClientNameNotBetween(String value1, String value2) {
			addCriterion("client_name not between", value1, value2, "clientName");
			return (Criteria) this;
		}

		public Criteria andClientTypeIsNull() {
			addCriterion("client_type is null");
			return (Criteria) this;
		}

		public Criteria andClientTypeIsNotNull() {
			addCriterion("client_type is not null");
			return (Criteria) this;
		}

		public Criteria andClientTypeEqualTo(String value) {
			addCriterion("client_type =", value, "clientType");
			return (Criteria) this;
		}

		public Criteria andClientTypeNotEqualTo(String value) {
			addCriterion("client_type <>", value, "clientType");
			return (Criteria) this;
		}

		public Criteria andClientTypeGreaterThan(String value) {
			addCriterion("client_type >", value, "clientType");
			return (Criteria) this;
		}

		public Criteria andClientTypeGreaterThanOrEqualTo(String value) {
			addCriterion("client_type >=", value, "clientType");
			return (Criteria) this;
		}

		public Criteria andClientTypeLessThan(String value) {
			addCriterion("client_type <", value, "clientType");
			return (Criteria) this;
		}

		public Criteria andClientTypeLessThanOrEqualTo(String value) {
			addCriterion("client_type <=", value, "clientType");
			return (Criteria) this;
		}

		public Criteria andClientTypeLike(String value) {
			addCriterion("client_type like", value, "clientType");
			return (Criteria) this;
		}

		public Criteria andClientTypeNotLike(String value) {
			addCriterion("client_type not like", value, "clientType");
			return (Criteria) this;
		}

		public Criteria andClientTypeIn(List<String> values) {
			addCriterion("client_type in", values, "clientType");
			return (Criteria) this;
		}

		public Criteria andClientTypeNotIn(List<String> values) {
			addCriterion("client_type not in", values, "clientType");
			return (Criteria) this;
		}

		public Criteria andClientTypeBetween(String value1, String value2) {
			addCriterion("client_type between", value1, value2, "clientType");
			return (Criteria) this;
		}

		public Criteria andClientTypeNotBetween(String value1, String value2) {
			addCriterion("client_type not between", value1, value2, "clientType");
			return (Criteria) this;
		}

		public Criteria andIsActiveIsNull() {
			addCriterion("is_active is null");
			return (Criteria) this;
		}

		public Criteria andIsActiveIsNotNull() {
			addCriterion("is_active is not null");
			return (Criteria) this;
		}

		public Criteria andIsActiveEqualTo(String value) {
			addCriterion("is_active =", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveNotEqualTo(String value) {
			addCriterion("is_active <>", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveGreaterThan(String value) {
			addCriterion("is_active >", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveGreaterThanOrEqualTo(String value) {
			addCriterion("is_active >=", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveLessThan(String value) {
			addCriterion("is_active <", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveLessThanOrEqualTo(String value) {
			addCriterion("is_active <=", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveLike(String value) {
			addCriterion("is_active like", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveNotLike(String value) {
			addCriterion("is_active not like", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveIn(List<String> values) {
			addCriterion("is_active in", values, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveNotIn(List<String> values) {
			addCriterion("is_active not in", values, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveBetween(String value1, String value2) {
			addCriterion("is_active between", value1, value2, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveNotBetween(String value1, String value2) {
			addCriterion("is_active not between", value1, value2, "isActive");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table client_master
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table client_master
     *
     * @mbg.generated do_not_delete_during_merge Sun Jan 27 22:24:47 IST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}