package com.cs.entities;

public class ClientMaster extends BaseEntity{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_master.client_id
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	private Integer clientId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_master.client_name
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	private String clientName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_master.client_type
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	private String clientType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_master.is_active
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	private String isActive;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_master.client_id
	 * @return  the value of client_master.client_id
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public Integer getClientId() {
		return clientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_master.client_id
	 * @param clientId  the value for client_master.client_id
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_master.client_name
	 * @return  the value of client_master.client_name
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public String getClientName() {
		return clientName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_master.client_name
	 * @param clientName  the value for client_master.client_name
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setClientName(String clientName) {
		this.clientName = clientName == null ? null : clientName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_master.client_type
	 * @return  the value of client_master.client_type
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public String getClientType() {
		return clientType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_master.client_type
	 * @param clientType  the value for client_master.client_type
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setClientType(String clientType) {
		this.clientType = clientType == null ? null : clientType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_master.is_active
	 * @return  the value of client_master.is_active
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public String getIsActive() {
		return isActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_master.is_active
	 * @param isActive  the value for client_master.is_active
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setIsActive(String isActive) {
		this.isActive = isActive == null ? null : isActive.trim();
	}
}