package com.cs.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExecutionOrderTxnExample extends BaseEntityExample{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public ExecutionOrderTxnExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("order_id is null");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("order_id is not null");
			return (Criteria) this;
		}

		public Criteria andOrderIdEqualTo(Integer value) {
			addCriterion("order_id =", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotEqualTo(Integer value) {
			addCriterion("order_id <>", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThan(Integer value) {
			addCriterion("order_id >", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_id >=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThan(Integer value) {
			addCriterion("order_id <", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
			addCriterion("order_id <=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIn(List<Integer> values) {
			addCriterion("order_id in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotIn(List<Integer> values) {
			addCriterion("order_id not in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdBetween(Integer value1, Integer value2) {
			addCriterion("order_id between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
			addCriterion("order_id not between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdIsNull() {
			addCriterion("execution_id is null");
			return (Criteria) this;
		}

		public Criteria andExecutionIdIsNotNull() {
			addCriterion("execution_id is not null");
			return (Criteria) this;
		}

		public Criteria andExecutionIdEqualTo(Integer value) {
			addCriterion("execution_id =", value, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdNotEqualTo(Integer value) {
			addCriterion("execution_id <>", value, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdGreaterThan(Integer value) {
			addCriterion("execution_id >", value, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("execution_id >=", value, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdLessThan(Integer value) {
			addCriterion("execution_id <", value, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdLessThanOrEqualTo(Integer value) {
			addCriterion("execution_id <=", value, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdIn(List<Integer> values) {
			addCriterion("execution_id in", values, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdNotIn(List<Integer> values) {
			addCriterion("execution_id not in", values, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdBetween(Integer value1, Integer value2) {
			addCriterion("execution_id between", value1, value2, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdNotBetween(Integer value1, Integer value2) {
			addCriterion("execution_id not between", value1, value2, "executionId");
			return (Criteria) this;
		}

		public Criteria andDistributedOrderIsNull() {
			addCriterion("distributed_order is null");
			return (Criteria) this;
		}

		public Criteria andDistributedOrderIsNotNull() {
			addCriterion("distributed_order is not null");
			return (Criteria) this;
		}

		public Criteria andDistributedOrderEqualTo(Float value) {
			addCriterion("distributed_order =", value, "distributedOrder");
			return (Criteria) this;
		}

		public Criteria andDistributedOrderNotEqualTo(Float value) {
			addCriterion("distributed_order <>", value, "distributedOrder");
			return (Criteria) this;
		}

		public Criteria andDistributedOrderGreaterThan(Float value) {
			addCriterion("distributed_order >", value, "distributedOrder");
			return (Criteria) this;
		}

		public Criteria andDistributedOrderGreaterThanOrEqualTo(Float value) {
			addCriterion("distributed_order >=", value, "distributedOrder");
			return (Criteria) this;
		}

		public Criteria andDistributedOrderLessThan(Float value) {
			addCriterion("distributed_order <", value, "distributedOrder");
			return (Criteria) this;
		}

		public Criteria andDistributedOrderLessThanOrEqualTo(Float value) {
			addCriterion("distributed_order <=", value, "distributedOrder");
			return (Criteria) this;
		}

		public Criteria andDistributedOrderIn(List<Float> values) {
			addCriterion("distributed_order in", values, "distributedOrder");
			return (Criteria) this;
		}

		public Criteria andDistributedOrderNotIn(List<Float> values) {
			addCriterion("distributed_order not in", values, "distributedOrder");
			return (Criteria) this;
		}

		public Criteria andDistributedOrderBetween(Float value1, Float value2) {
			addCriterion("distributed_order between", value1, value2, "distributedOrder");
			return (Criteria) this;
		}

		public Criteria andDistributedOrderNotBetween(Float value1, Float value2) {
			addCriterion("distributed_order not between", value1, value2, "distributedOrder");
			return (Criteria) this;
		}

		public Criteria andExecutionDateIsNull() {
			addCriterion("execution_Date is null");
			return (Criteria) this;
		}

		public Criteria andExecutionDateIsNotNull() {
			addCriterion("execution_Date is not null");
			return (Criteria) this;
		}

		public Criteria andExecutionDateEqualTo(Date value) {
			addCriterion("execution_Date =", value, "executionDate");
			return (Criteria) this;
		}

		public Criteria andExecutionDateNotEqualTo(Date value) {
			addCriterion("execution_Date <>", value, "executionDate");
			return (Criteria) this;
		}

		public Criteria andExecutionDateGreaterThan(Date value) {
			addCriterion("execution_Date >", value, "executionDate");
			return (Criteria) this;
		}

		public Criteria andExecutionDateGreaterThanOrEqualTo(Date value) {
			addCriterion("execution_Date >=", value, "executionDate");
			return (Criteria) this;
		}

		public Criteria andExecutionDateLessThan(Date value) {
			addCriterion("execution_Date <", value, "executionDate");
			return (Criteria) this;
		}

		public Criteria andExecutionDateLessThanOrEqualTo(Date value) {
			addCriterion("execution_Date <=", value, "executionDate");
			return (Criteria) this;
		}

		public Criteria andExecutionDateIn(List<Date> values) {
			addCriterion("execution_Date in", values, "executionDate");
			return (Criteria) this;
		}

		public Criteria andExecutionDateNotIn(List<Date> values) {
			addCriterion("execution_Date not in", values, "executionDate");
			return (Criteria) this;
		}

		public Criteria andExecutionDateBetween(Date value1, Date value2) {
			addCriterion("execution_Date between", value1, value2, "executionDate");
			return (Criteria) this;
		}

		public Criteria andExecutionDateNotBetween(Date value1, Date value2) {
			addCriterion("execution_Date not between", value1, value2, "executionDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table execution_order_txn
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table execution_order_txn
     *
     * @mbg.generated do_not_delete_during_merge Mon Jan 28 09:15:07 IST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}