package com.cs.entities;

import java.util.Date;

public class ExecutionOrderTxn extends BaseEntity{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column execution_order_txn.order_id
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column execution_order_txn.execution_id
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	private Integer executionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column execution_order_txn.distributed_order
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	private Float distributedOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column execution_order_txn.execution_Date
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	private Date executionDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column execution_order_txn.order_id
	 * @return  the value of execution_order_txn.order_id
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column execution_order_txn.order_id
	 * @param orderId  the value for execution_order_txn.order_id
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column execution_order_txn.execution_id
	 * @return  the value of execution_order_txn.execution_id
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public Integer getExecutionId() {
		return executionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column execution_order_txn.execution_id
	 * @param executionId  the value for execution_order_txn.execution_id
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setExecutionId(Integer executionId) {
		this.executionId = executionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column execution_order_txn.distributed_order
	 * @return  the value of execution_order_txn.distributed_order
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public Float getDistributedOrder() {
		return distributedOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column execution_order_txn.distributed_order
	 * @param distributedOrder  the value for execution_order_txn.distributed_order
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setDistributedOrder(Float distributedOrder) {
		this.distributedOrder = distributedOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column execution_order_txn.execution_Date
	 * @return  the value of execution_order_txn.execution_Date
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public Date getExecutionDate() {
		return executionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column execution_order_txn.execution_Date
	 * @param executionDate  the value for execution_order_txn.execution_Date
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setExecutionDate(Date executionDate) {
		this.executionDate = executionDate;
	}
}