package com.cs.entities;

public class ExecutionMst extends BaseEntity{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column execution_mst.execution_id
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	private Integer executionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column execution_mst.quantity
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	private Float quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column execution_mst.price
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column execution_mst.is_execution_available
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	private String isExecutionAvailable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column execution_mst.instrument_id
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	private Integer instrumentId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column execution_mst.execution_id
	 * @return  the value of execution_mst.execution_id
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public Integer getExecutionId() {
		return executionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column execution_mst.execution_id
	 * @param executionId  the value for execution_mst.execution_id
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public void setExecutionId(Integer executionId) {
		this.executionId = executionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column execution_mst.quantity
	 * @return  the value of execution_mst.quantity
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public Float getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column execution_mst.quantity
	 * @param quantity  the value for execution_mst.quantity
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public void setQuantity(Float quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column execution_mst.price
	 * @return  the value of execution_mst.price
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column execution_mst.price
	 * @param price  the value for execution_mst.price
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column execution_mst.is_execution_available
	 * @return  the value of execution_mst.is_execution_available
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public String getIsExecutionAvailable() {
		return isExecutionAvailable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column execution_mst.is_execution_available
	 * @param isExecutionAvailable  the value for execution_mst.is_execution_available
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public void setIsExecutionAvailable(String isExecutionAvailable) {
		this.isExecutionAvailable = isExecutionAvailable == null ? null : isExecutionAvailable.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column execution_mst.instrument_id
	 * @return  the value of execution_mst.instrument_id
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public Integer getInstrumentId() {
		return instrumentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column execution_mst.instrument_id
	 * @param instrumentId  the value for execution_mst.instrument_id
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public void setInstrumentId(Integer instrumentId) {
		this.instrumentId = instrumentId;
	}
}