package com.cs.entities;

import java.util.ArrayList;
import java.util.List;

public class ExecutionMstExample extends BaseEntityExample{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public ExecutionMstExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andExecutionIdIsNull() {
			addCriterion("execution_id is null");
			return (Criteria) this;
		}

		public Criteria andExecutionIdIsNotNull() {
			addCriterion("execution_id is not null");
			return (Criteria) this;
		}

		public Criteria andExecutionIdEqualTo(Integer value) {
			addCriterion("execution_id =", value, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdNotEqualTo(Integer value) {
			addCriterion("execution_id <>", value, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdGreaterThan(Integer value) {
			addCriterion("execution_id >", value, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("execution_id >=", value, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdLessThan(Integer value) {
			addCriterion("execution_id <", value, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdLessThanOrEqualTo(Integer value) {
			addCriterion("execution_id <=", value, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdIn(List<Integer> values) {
			addCriterion("execution_id in", values, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdNotIn(List<Integer> values) {
			addCriterion("execution_id not in", values, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdBetween(Integer value1, Integer value2) {
			addCriterion("execution_id between", value1, value2, "executionId");
			return (Criteria) this;
		}

		public Criteria andExecutionIdNotBetween(Integer value1, Integer value2) {
			addCriterion("execution_id not between", value1, value2, "executionId");
			return (Criteria) this;
		}

		public Criteria andQuantityIsNull() {
			addCriterion("quantity is null");
			return (Criteria) this;
		}

		public Criteria andQuantityIsNotNull() {
			addCriterion("quantity is not null");
			return (Criteria) this;
		}

		public Criteria andQuantityEqualTo(Float value) {
			addCriterion("quantity =", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityNotEqualTo(Float value) {
			addCriterion("quantity <>", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityGreaterThan(Float value) {
			addCriterion("quantity >", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityGreaterThanOrEqualTo(Float value) {
			addCriterion("quantity >=", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityLessThan(Float value) {
			addCriterion("quantity <", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityLessThanOrEqualTo(Float value) {
			addCriterion("quantity <=", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityIn(List<Float> values) {
			addCriterion("quantity in", values, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityNotIn(List<Float> values) {
			addCriterion("quantity not in", values, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityBetween(Float value1, Float value2) {
			addCriterion("quantity between", value1, value2, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityNotBetween(Float value1, Float value2) {
			addCriterion("quantity not between", value1, value2, "quantity");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Double value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Double value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Double value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Double value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Double value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Double> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Double> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Double value1, Double value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Double value1, Double value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andIsExecutionAvailableIsNull() {
			addCriterion("is_execution_available is null");
			return (Criteria) this;
		}

		public Criteria andIsExecutionAvailableIsNotNull() {
			addCriterion("is_execution_available is not null");
			return (Criteria) this;
		}

		public Criteria andIsExecutionAvailableEqualTo(String value) {
			addCriterion("is_execution_available =", value, "isExecutionAvailable");
			return (Criteria) this;
		}

		public Criteria andIsExecutionAvailableNotEqualTo(String value) {
			addCriterion("is_execution_available <>", value, "isExecutionAvailable");
			return (Criteria) this;
		}

		public Criteria andIsExecutionAvailableGreaterThan(String value) {
			addCriterion("is_execution_available >", value, "isExecutionAvailable");
			return (Criteria) this;
		}

		public Criteria andIsExecutionAvailableGreaterThanOrEqualTo(String value) {
			addCriterion("is_execution_available >=", value, "isExecutionAvailable");
			return (Criteria) this;
		}

		public Criteria andIsExecutionAvailableLessThan(String value) {
			addCriterion("is_execution_available <", value, "isExecutionAvailable");
			return (Criteria) this;
		}

		public Criteria andIsExecutionAvailableLessThanOrEqualTo(String value) {
			addCriterion("is_execution_available <=", value, "isExecutionAvailable");
			return (Criteria) this;
		}

		public Criteria andIsExecutionAvailableLike(String value) {
			addCriterion("is_execution_available like", value, "isExecutionAvailable");
			return (Criteria) this;
		}

		public Criteria andIsExecutionAvailableNotLike(String value) {
			addCriterion("is_execution_available not like", value, "isExecutionAvailable");
			return (Criteria) this;
		}

		public Criteria andIsExecutionAvailableIn(List<String> values) {
			addCriterion("is_execution_available in", values, "isExecutionAvailable");
			return (Criteria) this;
		}

		public Criteria andIsExecutionAvailableNotIn(List<String> values) {
			addCriterion("is_execution_available not in", values, "isExecutionAvailable");
			return (Criteria) this;
		}

		public Criteria andIsExecutionAvailableBetween(String value1, String value2) {
			addCriterion("is_execution_available between", value1, value2, "isExecutionAvailable");
			return (Criteria) this;
		}

		public Criteria andIsExecutionAvailableNotBetween(String value1, String value2) {
			addCriterion("is_execution_available not between", value1, value2, "isExecutionAvailable");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdIsNull() {
			addCriterion("instrument_id is null");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdIsNotNull() {
			addCriterion("instrument_id is not null");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdEqualTo(Integer value) {
			addCriterion("instrument_id =", value, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdNotEqualTo(Integer value) {
			addCriterion("instrument_id <>", value, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdGreaterThan(Integer value) {
			addCriterion("instrument_id >", value, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("instrument_id >=", value, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdLessThan(Integer value) {
			addCriterion("instrument_id <", value, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdLessThanOrEqualTo(Integer value) {
			addCriterion("instrument_id <=", value, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdIn(List<Integer> values) {
			addCriterion("instrument_id in", values, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdNotIn(List<Integer> values) {
			addCriterion("instrument_id not in", values, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdBetween(Integer value1, Integer value2) {
			addCriterion("instrument_id between", value1, value2, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdNotBetween(Integer value1, Integer value2) {
			addCriterion("instrument_id not between", value1, value2, "instrumentId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table execution_mst
	 * @mbg.generated  Mon Jan 28 10:43:29 IST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table execution_mst
     *
     * @mbg.generated do_not_delete_during_merge Mon Jan 28 09:15:07 IST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}