package com.cs.entities;

public class InstrumentMst extends BaseEntity{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column instrument_mst.instrument_id
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	private Integer instrumentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column instrument_mst.instrument_desc
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	private String instrumentDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column instrument_mst.is_active
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	private String isActive;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column instrument_mst.instrument_id
	 * @return  the value of instrument_mst.instrument_id
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public Integer getInstrumentId() {
		return instrumentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column instrument_mst.instrument_id
	 * @param instrumentId  the value for instrument_mst.instrument_id
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setInstrumentId(Integer instrumentId) {
		this.instrumentId = instrumentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column instrument_mst.instrument_desc
	 * @return  the value of instrument_mst.instrument_desc
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public String getInstrumentDesc() {
		return instrumentDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column instrument_mst.instrument_desc
	 * @param instrumentDesc  the value for instrument_mst.instrument_desc
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setInstrumentDesc(String instrumentDesc) {
		this.instrumentDesc = instrumentDesc == null ? null : instrumentDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column instrument_mst.is_active
	 * @return  the value of instrument_mst.is_active
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public String getIsActive() {
		return isActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column instrument_mst.is_active
	 * @param isActive  the value for instrument_mst.is_active
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setIsActive(String isActive) {
		this.isActive = isActive == null ? null : isActive.trim();
	}
}