package com.cs.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderBookExample extends BaseEntityExample{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public OrderBookExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("order_id is null");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("order_id is not null");
			return (Criteria) this;
		}

		public Criteria andOrderIdEqualTo(Integer value) {
			addCriterion("order_id =", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotEqualTo(Integer value) {
			addCriterion("order_id <>", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThan(Integer value) {
			addCriterion("order_id >", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_id >=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThan(Integer value) {
			addCriterion("order_id <", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
			addCriterion("order_id <=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIn(List<Integer> values) {
			addCriterion("order_id in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotIn(List<Integer> values) {
			addCriterion("order_id not in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdBetween(Integer value1, Integer value2) {
			addCriterion("order_id between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
			addCriterion("order_id not between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andClientIdIsNull() {
			addCriterion("client_id is null");
			return (Criteria) this;
		}

		public Criteria andClientIdIsNotNull() {
			addCriterion("client_id is not null");
			return (Criteria) this;
		}

		public Criteria andClientIdEqualTo(Integer value) {
			addCriterion("client_id =", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdNotEqualTo(Integer value) {
			addCriterion("client_id <>", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdGreaterThan(Integer value) {
			addCriterion("client_id >", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("client_id >=", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdLessThan(Integer value) {
			addCriterion("client_id <", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdLessThanOrEqualTo(Integer value) {
			addCriterion("client_id <=", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdIn(List<Integer> values) {
			addCriterion("client_id in", values, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdNotIn(List<Integer> values) {
			addCriterion("client_id not in", values, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdBetween(Integer value1, Integer value2) {
			addCriterion("client_id between", value1, value2, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdNotBetween(Integer value1, Integer value2) {
			addCriterion("client_id not between", value1, value2, "clientId");
			return (Criteria) this;
		}

		public Criteria andQuantityIsNull() {
			addCriterion("quantity is null");
			return (Criteria) this;
		}

		public Criteria andQuantityIsNotNull() {
			addCriterion("quantity is not null");
			return (Criteria) this;
		}

		public Criteria andQuantityEqualTo(Integer value) {
			addCriterion("quantity =", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityNotEqualTo(Integer value) {
			addCriterion("quantity <>", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityGreaterThan(Integer value) {
			addCriterion("quantity >", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityGreaterThanOrEqualTo(Integer value) {
			addCriterion("quantity >=", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityLessThan(Integer value) {
			addCriterion("quantity <", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityLessThanOrEqualTo(Integer value) {
			addCriterion("quantity <=", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityIn(List<Integer> values) {
			addCriterion("quantity in", values, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityNotIn(List<Integer> values) {
			addCriterion("quantity not in", values, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityBetween(Integer value1, Integer value2) {
			addCriterion("quantity between", value1, value2, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityNotBetween(Integer value1, Integer value2) {
			addCriterion("quantity not between", value1, value2, "quantity");
			return (Criteria) this;
		}

		public Criteria andEntryDateIsNull() {
			addCriterion("entry_date is null");
			return (Criteria) this;
		}

		public Criteria andEntryDateIsNotNull() {
			addCriterion("entry_date is not null");
			return (Criteria) this;
		}

		public Criteria andEntryDateEqualTo(Date value) {
			addCriterion("entry_date =", value, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateNotEqualTo(Date value) {
			addCriterion("entry_date <>", value, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateGreaterThan(Date value) {
			addCriterion("entry_date >", value, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateGreaterThanOrEqualTo(Date value) {
			addCriterion("entry_date >=", value, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateLessThan(Date value) {
			addCriterion("entry_date <", value, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateLessThanOrEqualTo(Date value) {
			addCriterion("entry_date <=", value, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateIn(List<Date> values) {
			addCriterion("entry_date in", values, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateNotIn(List<Date> values) {
			addCriterion("entry_date not in", values, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateBetween(Date value1, Date value2) {
			addCriterion("entry_date between", value1, value2, "entryDate");
			return (Criteria) this;
		}

		public Criteria andEntryDateNotBetween(Date value1, Date value2) {
			addCriterion("entry_date not between", value1, value2, "entryDate");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Double value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Double value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Double value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Double value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Double value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Double> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Double> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Double value1, Double value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Double value1, Double value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdIsNull() {
			addCriterion("instrument_id is null");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdIsNotNull() {
			addCriterion("instrument_id is not null");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdEqualTo(Integer value) {
			addCriterion("instrument_id =", value, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdNotEqualTo(Integer value) {
			addCriterion("instrument_id <>", value, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdGreaterThan(Integer value) {
			addCriterion("instrument_id >", value, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("instrument_id >=", value, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdLessThan(Integer value) {
			addCriterion("instrument_id <", value, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdLessThanOrEqualTo(Integer value) {
			addCriterion("instrument_id <=", value, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdIn(List<Integer> values) {
			addCriterion("instrument_id in", values, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdNotIn(List<Integer> values) {
			addCriterion("instrument_id not in", values, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdBetween(Integer value1, Integer value2) {
			addCriterion("instrument_id between", value1, value2, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andInstrumentIdNotBetween(Integer value1, Integer value2) {
			addCriterion("instrument_id not between", value1, value2, "instrumentId");
			return (Criteria) this;
		}

		public Criteria andIsOrderOpenIsNull() {
			addCriterion("is_order_open is null");
			return (Criteria) this;
		}

		public Criteria andIsOrderOpenIsNotNull() {
			addCriterion("is_order_open is not null");
			return (Criteria) this;
		}

		public Criteria andIsOrderOpenEqualTo(String value) {
			addCriterion("is_order_open =", value, "isOrderOpen");
			return (Criteria) this;
		}

		public Criteria andIsOrderOpenNotEqualTo(String value) {
			addCriterion("is_order_open <>", value, "isOrderOpen");
			return (Criteria) this;
		}

		public Criteria andIsOrderOpenGreaterThan(String value) {
			addCriterion("is_order_open >", value, "isOrderOpen");
			return (Criteria) this;
		}

		public Criteria andIsOrderOpenGreaterThanOrEqualTo(String value) {
			addCriterion("is_order_open >=", value, "isOrderOpen");
			return (Criteria) this;
		}

		public Criteria andIsOrderOpenLessThan(String value) {
			addCriterion("is_order_open <", value, "isOrderOpen");
			return (Criteria) this;
		}

		public Criteria andIsOrderOpenLessThanOrEqualTo(String value) {
			addCriterion("is_order_open <=", value, "isOrderOpen");
			return (Criteria) this;
		}

		public Criteria andIsOrderOpenLike(String value) {
			addCriterion("is_order_open like", value, "isOrderOpen");
			return (Criteria) this;
		}

		public Criteria andIsOrderOpenNotLike(String value) {
			addCriterion("is_order_open not like", value, "isOrderOpen");
			return (Criteria) this;
		}

		public Criteria andIsOrderOpenIn(List<String> values) {
			addCriterion("is_order_open in", values, "isOrderOpen");
			return (Criteria) this;
		}

		public Criteria andIsOrderOpenNotIn(List<String> values) {
			addCriterion("is_order_open not in", values, "isOrderOpen");
			return (Criteria) this;
		}

		public Criteria andIsOrderOpenBetween(String value1, String value2) {
			addCriterion("is_order_open between", value1, value2, "isOrderOpen");
			return (Criteria) this;
		}

		public Criteria andIsOrderOpenNotBetween(String value1, String value2) {
			addCriterion("is_order_open not between", value1, value2, "isOrderOpen");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIsNull() {
			addCriterion("order_type is null");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIsNotNull() {
			addCriterion("order_type is not null");
			return (Criteria) this;
		}

		public Criteria andOrderTypeEqualTo(String value) {
			addCriterion("order_type =", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotEqualTo(String value) {
			addCriterion("order_type <>", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeGreaterThan(String value) {
			addCriterion("order_type >", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeGreaterThanOrEqualTo(String value) {
			addCriterion("order_type >=", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeLessThan(String value) {
			addCriterion("order_type <", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeLessThanOrEqualTo(String value) {
			addCriterion("order_type <=", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeLike(String value) {
			addCriterion("order_type like", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotLike(String value) {
			addCriterion("order_type not like", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIn(List<String> values) {
			addCriterion("order_type in", values, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotIn(List<String> values) {
			addCriterion("order_type not in", values, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeBetween(String value1, String value2) {
			addCriterion("order_type between", value1, value2, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotBetween(String value1, String value2) {
			addCriterion("order_type not between", value1, value2, "orderType");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table order_book
	 * @mbg.generated  Mon Jan 28 10:12:46 IST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_book
     *
     * @mbg.generated do_not_delete_during_merge Mon Jan 28 09:15:07 IST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}